Fix an error that makes the width value string very long.
mbrn/material-table pull request #2441
Opened 2020-09-10 17:09 UTC by JongtaekChoi

## Related Issue

#2433 (not sure)

## Description

`columnDef.tableData.width`may be defined even  if `columnDef.width` is undefined.
Because the calculated `tableData.width` added to each `column` object when the props updated or added.
This function produces a string value with a previously calculated value each time it is called, so the length increases proportionally to the power of the number of columns with has undefined width.
<img width="659" alt="스크린샷 2020-09-11 오전 2 03 40" src="https://user-images.githubusercontent.com/17980230/92768516-0c67ce00-f3d3-11ea-91aa-f2d9113476a5.png">

2020-09-14 07:30 UTC, cdruck requested changes
lines 87 and 88 are inconsistent

2020-09-17 07:21 UTC, JongtaekChoi commented
> lines 87 and 88 are inconsistent

How about this way?

2020-10-03 01:26 UTC, joacub reviewed
does not work still the bug

2020-10-03 02:16 UTC, joacub requested changes
the problem is this:
**OLD WRONG:**
```js
columnDef.tableData = {
        columnOrder: index,
        filterValue: columnDef.defaultFilter,
        groupOrder: columnDef.defaultGroupOrder,
        groupSort: columnDef.defaultGroupSort || 'asc',
        width: typeof columnDef.width === 'number' ? `${columnDef.width}px` : columnDef.width,
        initialWidth: typeof columnDef.width === 'number' ? `${columnDef.width}px` : columnDef.width,
        additionalWidth: 0,
        id: index,
       **...columnDef.tableData,** <------------------------------------  Mutable data overwrite the width
      };
```

```js
columnDef.tableData = {
        **...columnDef.tableData,** <------------------------------------  Now mutable data is overwrites by the next code
        columnOrder: index,
        filterValue: columnDef.defaultFilter,
        groupOrder: columnDef.defaultGroupOrder,
        groupSort: columnDef.defaultGroupSort || 'asc',
        width: typeof columnDef.width === 'number' ? `${columnDef.width}px` : columnDef.width,
        initialWidth: typeof columnDef.width === 'number' ? `${columnDef.width}px` : columnDef.width,
        additionalWidth: 0,
        id: index,
      };
```

2020-11-16 03:23 UTC, justrhysism commented
I applied this patch manually and it resolved the issue from what I could see.

2021-02-21 06:42 UTC, closed without merging